# Generated by Django 5.2 on 2025-05-02 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_api', '0001_initial'),
        ('crud_api_app', '__first__'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='products',
            field=models.ManyToManyField(through='crud_api.TransactionItem', to='crud_api_app.products'),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_api.transaction'),
        ),
    ]
