# Generated by Django 5.2 on 2025-05-02 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_api', '0002_rename_products_product_alter_transaction_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='products',
            field=models.ManyToManyField(through='crud_api.TransactionItem', to='crud_api.product'),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_api.product'),
        ),
    ]
